=== GeoThai/data/schemas/v1/districts.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "number"
      },
      "province_id": {
        "type": "number"
      },
      "district_id": {
        "type": "number"
      },
      "district_name_en": {
        "type": "string"
      },
      "district_name_th": {
        "type": "string"
      },
      "postal_code": {
        "type": "number"
      }
    },
    "required": [
      "id",
      "province_id",
      "district_id",
      "district_name_en",
      "district_name_th",
      "postal_code"
    ]
  }
}

=== GeoThai/data/data/v1/districts.json
[
  {
    "id": 1,
    "province_id": 10,
    "district_id": 1001,
    "district_name_en": "Phra Nakhon",
    "district_name_th": "พระนคร",
    "postal_code": 10200
  },
  {
    "id": 2,
    "province_id": 10,
    "district_id": 1002,
    "district_name_en": "Dusit",
    "district_name_th": "ดุสิต",
    "postal_code": 10300
  },
  {
    "id": 3,
    "province_id": 10,
    "district_id": 1003,
    "district_name_en": "Nong Chok",
    "district_name_th": "หนองจอก",
    "postal_code": 10530
  },
  {
    "id": 4,
    "province_id": 10,
    "district_id": 1004,
    "district_name_en": "Bang Rak",
    "district_name_th": "บางรัก",
    "postal_code": 10500
  },
  {
    "id": 5,
    "province_id": 10,
    "district_id": 1005,
    "district_name_en": "Bang Khen",
    "district_name_th": "บางเขน",
    "postal_code": 10220
  },
  {
    "id": 6,
    "province_id": 10,
    "district_id": 1006,
    "district_name_en": "Bang Kapi",
    "district_name_th": "บางกะปิ",
    "postal_code": 10240
  },
  {
    "id": 7,
    "province_id": 10,
    "district_id": 1007,
    "district_name_en": "Pathum Wan",
    "district_name_th": "ปทุมวัน",
    "postal_code": 10330
  },
  {
    "id": 8,
    "province_id": 10,
    "district_id": 1008,
    "district_name_en": "Pom Prap Sattruphai",
    "district_name_th": "ป้อมปราบศัตรูพ่าย",
    "postal_code": 10100
  },
  {
    "id": 9,
    "province_id": 10,
    "district_id": 1009,
    "district_name_en": "Phra Khanong",
    "district_name_th": "พระโขนง",
    "postal_code": 10260
  },
  {
    "id": 10,
    "province_id": 10,
    "district_id": 1010,
    "district_name_en": "Min Buri",
    "district_name_th": "มีนบุรี",
    "postal_code": 10510
  },
  {
    "id": 11,
    "province_id": 10,
    "district_id": 1011,
    "district_name_en": "Lat Krabang",
    "district_name_th": "ลาดกระบัง",
    "postal_code": 10520
  },
  {
    "id": 12,
    "province_id": 10,
    "district_id": 1012,
    "district_name_en": "Yannawa",
    "district_name_th": "ยานนาวา",
    "postal_code": 10120
  },
  {
    "id": 13,
    "province_id": 10,
    "district_id": 1013,
    "district_name_en": "Samphanthawong",
    "district_name_th": "สัมพันธวงศ์",
    "postal_code": 10100
  },
  {
    "id": 14,
    "province_id": 10,
    "district_id": 1014,
    "district_name_en": "Phaya Thai",
    "district_name_th": "พญาไท",
    "postal_code": 10400
  },
  {
    "id": 15,
    "province_id": 10,
    "district_id": 1015,
    "district_name_en": "Thon Buri",
    "district_name_th": "ธนบุรี",
    "postal_code": 10600
  },
  {
    "id": 16,
    "province_id": 10,
    "district_id": 1016,
    "district_name_en": "Bangkok Yai",
    "district_name_th": "บางกอกใหญ่",
    "postal_code": 10600
  },
  {
    "id": 17,
    "province_id": 10,
    "district_id": 1017,
    "district_name_en": "Huai Khwang",
    "district_name_th": "ห้วยขวาง",
    "postal_code": 10310
  },
  {
    "id": 18,
    "province_id": 10,
    "district_id": 1018,
    "district_name_en": "Khlong San",
    "district_name_th": "คลองสาน",
    "postal_code": 10600
  },
  {
    "id": 19,
    "province_id": 10,
    "district_id": 1019,
    "district_name_en": "Taling Chan",
    "district_name_th": "ตลิ่งชัน",
    "postal_code": 10170
  },
  {
    "id": 20,
    "province_id": 10,
    "district_id": 1020,
    "district_name_en": "Bangkok Noi",
    "district_name_th": "บางกอกน้อย",
    "postal_code": 10700
  },
  {
    "id": 21,
    "province_id": 10,
    "district_id": 1021,
    "district_name_en": "Bang Khun Thian",
    "district_name_th": "บางขุนเทียน",
    "postal_code": 10150
  },
  {
    "id": 22,
    "province_id": 10,
    "district_id": 1022,
    "district_name_en": "Phasi Charoen",
    "district_name_th": "ภาษีเจริญ",
    "postal_code": 10160
  },
  {
    "id": 23,
    "province_id": 10,
    "district_id": 1023,
    "district_name_en": "Nong Khaem",
    "district_name_th": "หนองแขม",
    "postal_code": 10160
  },
  {
    "id": 24,
    "province_id": 10,
    "district_id": 1024,
    "district_name_en": "Rat Burana",
    "district_name_th": "ราษฎร์บูรณะ",
    "postal_code": 10140
  },
  {
    "id": 25,
    "province_id": 10,
    "district_id": 1025,
    "district_name_en": "Bang Phlat",
    "district_name_th": "บางพลัด",
    "postal_code": 10700
  },
  {
    "id": 26,
    "province_id": 10,
    "district_id": 1026,
    "district_name_en": "Din Daeng",
    "district_name_th": "ดินแดง",
    "postal_code": 10400
  },
  {
    "id": 27,
    "province_id": 10,
    "district_id": 1027,
    "district_name_en": "Bung Kum",
    "district_name_th": "บึงกุ่ม",
    "postal_code": 10240
  },
  {
    "id": 28,
    "province_id": 10,
    "district_id": 1028,
    "district_name_en": "Sa Thon",
    "district_name_th": "สาทร",
    "postal_code": 10120
  },
  {
    "id": 29,
    "province_id": 10,
    "district_id": 1029,
    "district_name_en": "Bang Su",
    "district_name_th": "บางซื่อ",
    "postal_code": 10800
  },
  {
    "id": 30,
    "province_id": 10,
    "district_id": 1030,
    "district_name_en": "Chatuchak",
    "district_name_th": "จตุจักร",
    "postal_code": 10900
  },
  {
    "id": 31,
    "province_id": 10,
    "district_id": 1031,
    "district_name_en": "Bang Kho Laem",
    "district_name_th": "บางคอแหลม",
    "postal_code": 10120
  },
  {
    "id": 32,
    "province_id": 10,
    "district_id": 1032,
    "district_name_en": "Prawet",
    "district_name_th": "ประเวศ",
    "postal_code": 10250
  },
  {
    "id": 33,
    "province_id": 10,
    "district_id": 1033,
    "district_name_en": "Khlong Toei",
    "district_name_th": "คลองเตย",
    "postal_code": 10110
  },
  {
    "id": 34,
    "province_id": 10,
    "district_id": 1034,
    "district_name_en": "Suan Luang",
    "district_name_th": "สวนหลวง",
    "postal_code": 10250
  },
  {
    "id": 35,
    "province_id": 10,
    "district_id": 1035,
    "district_name_en": "Chom Thong",
    "district_name_th": "จอมทอง",
    "postal_code": 10150
  },
  {
    "id": 36,
    "province_id": 10,
    "district_id": 1036,
    "district_name_en": "Don Mueang",
    "district_name_th": "ดอนเมือง",
    "postal_code": 10210
  },
  {
    "id": 37,
    "province_id": 10,
    "district_id": 1037,
    "district_name_en": "Ratchathewi",
    "district_name_th": "ราชเทวี",
    "postal_code": 10400
  },
  {
    "id": 38,
    "province_id": 10,
    "district_id": 1038,
    "district_name_en": "Lat Phrao",
    "district_name_th": "ลาดพร้าว",
    "postal_code": 10230
  },
  {
    "id": 39,
    "province_id": 10,
    "district_id": 1039,
    "district_name_en": "Watthana",
    "district_name_th": "วัฒนา",
    "postal_code": 10110
  },
  {
    "id": 40,
    "province_id": 10,
    "district_id": 1040,
    "district_name_en": "Bang Khae",
    "district_name_th": "บางแค",
    "postal_code": 10160
  },
  {
    "id": 41,
    "province_id": 10,
    "district_id": 1041,
    "district_name_en": "Lak Si",
    "district_name_th": "หลักสี่",
    "postal_code": 10210
  },
  {
    "id": 42,
    "province_id": 10,
    "district_id": 1042,
    "district_name_en": "Sai Mai",
    "district_name_th": "สายไหม",
    "postal_code": 10220
  },
  {
    "id": 43,
    "province_id": 10,
    "district_id": 1043,
    "district_name_en": "Khanna Yao",
    "district_name_th": "คันนายาว",
    "postal_code": 10230
  },
  {
    "id": 44,
    "province_id": 10,
    "district_id": 1044,
    "district_name_en": "Saphan Sung",
    "district_name_th": "สะพานสูง",
    "postal_code": 10240
  },
  {
    "id": 45,
    "province_id": 10,
    "district_id": 1045,
    "district_name_en": "Wang Thong Lang",
    "district_name_th": "วังทองหลาง",
    "postal_code": 10310
  },
  {
    "id": 46,
    "province_id": 10,
    "district_id": 1046,
    "district_name_en": "Khlong Sam Wa",
    "district_name_th": "คลองสามวา",
    "postal_code": 10510
  },
  {
    "id": 47,
    "province_id": 10,
    "district_id": 1047,
    "district_name_en": "Bang Na",
    "district_name_th": "บางนา",
    "postal_code": 10260
  },
  {
    "id": 48,
    "province_id": 10,
    "district_id": 1048,
    "district_name_en": "Thawi Watthana",
    "district_name_th": "ทวีวัฒนา",
    "postal_code": 10170
  },
  {
    "id": 49,
    "province_id": 10,
    "district_id": 1049,
    "district_name_en": "Thung Khu",
    "district_name_th": "ทุ่งครุ",
    "postal_code": 10140
  },
  {
    "id": 50,
    "province_id": 10,
    "district_id": 1050,
    "district_name_en": "Bang Bon",
    "district_name_th": "บางบอน",
    "postal_code": 10150
  },
  {
    "id": 51,
    "province_id": 11,
    "district_id": 1101,
    "district_name_en": "Mueang Samut Prakan",
    "district_name_th": "เมืองสมุทรปราการ",
    "postal_code": 10270
  },
  {
    "id": 52,
    "province_id": 11,
    "district_id": 1102,
    "district_name_en": "Bang Bo",
    "district_name_th": "บางบ่อ",
    "postal_code": 10560
  },
  {
    "id": 53,
    "province_id": 11,
    "district_id": 1103,
    "district_name_en": "Bang Phli",
    "district_name_th": "บางพลี",
    "postal_code": 10540
  },
  {
    "id": 54,
    "province_id": 11,
    "district_id": 1104,
    "district_name_en": "Phra Pradaeng",
    "district_name_th": "พระประแดง",
    "postal_code": 10130
  },
  {
    "id": 55,
    "province_id": 11,
    "district_id": 1105,
    "district_name_en": "Phra Samut Chedi",
    "district_name_th": "พระสมุทรเจดีย์",
    "postal_code": 10290
  },
  {
    "id": 56,
    "province_id": 11,
    "district_id": 1106,
    "district_name_en": "Bang Sao Thong",
    "district_name_th": "บางเสาธง",
    "postal_code": 10570
  },
  {
    "id": 57,
    "province_id": 12,
    "district_id": 1201,
    "district_name_en": "Mueang Nonthaburi",
    "district_name_th": "เมืองนนทบุรี",
    "postal_code": 11000
  },
  {
    "id": 58,
    "province_id": 12,
    "district_id": 1202,
    "district_name_en": "Bang Kruai",
    "district_name_th": "บางกรวย",
    "postal_code": 11130
  },
  {
    "id": 59,
    "province_id": 12,
    "district_id": 1203,
    "district_name_en": "Bang Yai",
